# Generated by Django 4.1.1 on 2023-06-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
