# Generated by Django 4.1.1 on 2023-06-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('stop', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorForTimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicators', models.ManyToManyField(to='webapp.indicator')),
                ('time_frame', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('first', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='currencypair1_set', to='common.currency')),
                ('last', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='currencypair2_set', to='common.currency')),
                ('time_window', models.ManyToManyField(to='webapp.timewindow')),
            ],
        ),
        migrations.CreateModel(
            name='ChartForTimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=30, unique=True)),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.currencypair')),
                ('time_frame', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.timeframe')),
            ],
        ),
    ]
