# Generated by Django 4.1.1 on 2023-06-12 11:03

import common.models
from django.db import migrations, models
import django.db.models.deletion
import utils.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=utils.django.custom_now)),
                ('updated_at', common.models.AutoDateTimeField(default=utils.django.custom_now)),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('binance_api_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('binance_secret_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ref_id', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('language_code', models.CharField(max_length=4)),
                ('language', models.CharField(default='english', max_length=10)),
                ('is_allowed', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=utils.django.custom_now)),
                ('updated_at', common.models.AutoDateTimeField(default=utils.django.custom_now)),
                ('tg_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.telegramprofile')),
            ],
        ),
    ]
